version: 2.0
jobs:
  test:
    steps:
      machine: true
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t $DOCKER_USER/ca-project:$CIRCLE_SHA1 .
    - run: docker push $DOCKER_USER/ca-project:$CIRCLE_SHA1

workflows:
  version: 2
  two_job_flow:
    jobs:
    - test
    - dockerize:
        requires:
        - test
    - deploy-product:
        requires:
        - dockerize
        filters:
          branches:
            only: master
