version: 2.0
jobs:
  test:
    machine: true
    steps:  
    - checkout
    - persist_to_workspace:
        root: .
        paths:
          - .
  dockerize:
    machine: true
    steps:
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t $DOCKER_USER/portfolio:$CIRCLE_SHA1 .
    - run: docker push $DOCKER_USER/portfolio:$CIRCLE_SHA1
  deploy-production:
    machine: true
    steps:
    - add_ssh_keys:
        fingerprints:
        - bc:f8:37:37:e7:c4:97:f1:6d:aa:9e:00:ed:84:d0:77
    - run: ssh root@$PROD_IP "docker run -d -p 80:80 ulriksandberg/portfolio:$CIRCLE_SHA1"
workflows:
  version: 2
  two_job_flow:
    jobs:
    - test
    - dockerize:
        requires:
        - test
    - deploy-production:
        requires:
        - dockerize
        filters:
          branches:
            only: master
