version: 2.0
jobs:
  test:
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .

workflows:
  version: 2
  one-stage-workflow:
    jobs:
      -test
     -dockerize:
        requires:
          -test