version: 2.0
jobs:
  test:
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  

workflows:
  version: 2
  one-stage-workflow:
    jobs:
      -test